# Generated by Django 3.0.7 on 2020-07-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daspf_app', '0004_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='body',
            field=models.TextField(default='Postare fără conținut', null=True),
        ),
    ]
