# Generated by Django 3.0.7 on 2020-07-23 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daspf_app', '0005_news_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='date_created',
            new_name='created_at',
        ),
    ]
