# Generated by Django 3.0.7 on 2020-08-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daspf_app', '0009_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
