# Generated by Django 3.0.8 on 2020-09-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daspf_app', '0011_auto_20200805_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('body', models.TextField(default='Pagină fără conținut', null=True)),
            ],
        ),
    ]
