# Generated by Django 3.0.8 on 2020-09-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daspf_app', '0012_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('N', 'Nou'), ('V', 'Văzut'), ('R', 'Răspuns'), ('S', 'Soluționat')], default='N', max_length=1),
        ),
    ]
