# Generated by Django 3.0.8 on 2020-09-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daspf_app', '0013_message_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
