# Generated by Django 3.0.8 on 2020-09-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daspf_app', '0014_message_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='response',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
