# Generated by Django 3.0.8 on 2020-09-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daspf_app', '0015_message_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
